{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toolbridge-mcpbridge.secretName" . }}
  labels:
    {{- include "toolbridge-mcpbridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.auth0SyncApiAudience }}
  auth0-sync-api-audience: {{ .Values.secrets.auth0SyncApiAudience | quote }}
  {{- else if .Values.mcpbridge.auth0.syncApiAudience }}
  auth0-sync-api-audience: {{ .Values.mcpbridge.auth0.syncApiAudience | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0ClientIdNative }}
  auth0-client-id-native: {{ .Values.secrets.auth0ClientIdNative | quote }}
  {{- else if .Values.mcpbridge.auth0.clientIdNative }}
  auth0-client-id-native: {{ .Values.mcpbridge.auth0.clientIdNative | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0ClientIdWeb }}
  auth0-client-id-web: {{ .Values.secrets.auth0ClientIdWeb | quote }}
  {{- else if .Values.mcpbridge.auth0.clientIdWeb }}
  auth0-client-id-web: {{ .Values.mcpbridge.auth0.clientIdWeb | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0ClientIdMacos }}
  auth0-client-id-macos: {{ .Values.secrets.auth0ClientIdMacos | quote }}
  {{- else if .Values.mcpbridge.auth0.clientIdMacos }}
  auth0-client-id-macos: {{ .Values.mcpbridge.auth0.clientIdMacos | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0IntrospectionClientId }}
  auth0-introspection-client-id: {{ .Values.secrets.auth0IntrospectionClientId | quote }}
  {{- else if .Values.mcpbridge.auth0.introspection.clientId }}
  auth0-introspection-client-id: {{ .Values.mcpbridge.auth0.introspection.clientId | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0IntrospectionClientSecret }}
  auth0-introspection-client-secret: {{ .Values.secrets.auth0IntrospectionClientSecret | quote }}
  {{- else if .Values.mcpbridge.auth0.introspection.clientSecret }}
  auth0-introspection-client-secret: {{ .Values.mcpbridge.auth0.introspection.clientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.auth0IntrospectionAudience }}
  auth0-introspection-audience: {{ .Values.secrets.auth0IntrospectionAudience | quote }}
  {{- else if .Values.mcpbridge.auth0.introspection.audience }}
  auth0-introspection-audience: {{ .Values.mcpbridge.auth0.introspection.audience | quote }}
  {{- end }}
{{- end }}
