{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toolbridge-mcp.secretName" . }}
  labels:
    {{- include "toolbridge-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSigningKey }}
  jwt-signing-key: {{ .Values.secrets.jwtSigningKey | quote }}
  {{- end }}
  # Placeholder to ensure secret is created even without jwt-signing-key
  # MCP can work without JWT signing key by using backend /auth/token-exchange
  _placeholder: "mcp-secret"
{{- end }}
